name: sano
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Provider
  provider: ^6.0.2
  # GetIt
  get_it: ^7.2.0
  # Moor
  moor_flutter: ^4.0.0
  # Rxdart
  rxdart: ^0.27.3
  # Path Provider
  path_provider: ^2.0.8
  dartz: ^0.10.1
  intl: ^0.17.0
  sqlite3_flutter_libs: ^0.5.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  moor_generator: ^4.2.2
  moor_db_viewer: any
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

